---
title: "242 Final Project"
author: "Lizzy Kinnard and Shelley Facente"
date: "November 21, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#open packages
library(here)
library(foreign)
library(labelled)
library(dplyr)
library(reshape2)
library(lme4)
library(MASS)
library(mice)
library(biostat3)
library(lmtest)
```

```{r dataload, include=FALSE}
#set working directory
setwd("~/Desktop/lizzyandshelley/Dataset") #LIZZY
#setwd("~/GitHub/lizzyandshelley/Dataset")  #SHELLEY

#load the data
df <- read.spss("Ricky.SAV", use.value.labels = TRUE, to.data.frame=TRUE)

#get variable labels
attr(df, "variable.labels")
df.labels <- as.data.frame(attr(df, "variable.labels"))
QDSlabels <- data.frame(rownames(df.labels))
df.labels <- cbind(QDSlabels, df.labels)
names(df.labels) <- c("VAR_ID", "description")
rm(QDSlabels)

#USE THIS CODE TO LOOK UP A VARIABLE DESCRIPTION
#df.labels$description[df.labels$VAR_ID=="GENDER"]

#create substance use indicators

# #crack injection
# table(df$CRKINJ, useNA = "ifany")

df$CRKINJ1 <- ifelse(df$CRKINJ1=="No", "No", ifelse(df$CRKINJ1=="Yes", "Yes", NA))
# table(df$CRKINJ1, useNA = "ifany")
# table(df$CRKINJ2, useNA = "ifany")
# 
# 
# #powder cocaine injection
# table(df$CCINJ, useNA = "ifany")

df$CCINJ1 <- ifelse(df$CCINJ1=="No", "No", ifelse(df$CCINJ1=="Yes", "Yes", NA))
# table(df$CCINJ1, useNA = "ifany")
# table(df$CCINJ2, useNA = "ifany")
# 
# 
# #meth injection
# table(df$MTINJ, useNA = "ifany")

df$MTINJ1 <- ifelse(df$MTINJ1=="No", "No", ifelse(df$MTINJ1=="Yes", "Yes", NA))

# table(df$MTINJ1, useNA = "ifany")
# table(df$MTINJ2, useNA = "ifany")
# 

#injection of prescription stimulants
#table(df$STINJ, useNA = "ifany")

df$STINJ1 <- ifelse(df$STINJ1=="No", "No", ifelse(df$STINJ1=="Yes", "Yes", NA))

#table(df$STINJ1, useNA = "ifany")
#table(df$STINJ2, useNA = "ifany")


# #heroin injection
# table(df$HRINJ, useNA = "ifany")

df$HRINJ1 <- ifelse(df$HRINJ1=="No", "No", ifelse(df$HRINJ1=="Yes", "Yes", NA))
# table(df$HRINJ1, useNA = "ifany")
# table(df$HRINJ2, useNA = "ifany")

#NMPO injection
table(df$OPINJ, useNA = "ifany")

df$OPINJ1 <- ifelse(df$OPINJ1=="No", "No", ifelse(df$OPINJ1=="Yes", "Yes", NA))
table(df$OPINJ1, useNA = "ifany")
table(df$OPINJ2, useNA = "ifany")
# 
# #alcohol
df$ALCDAY <- as.numeric(df$ALCDAY)
df$ALCDAY1 <- as.numeric(df$ALCDAY1)
df$ALCDAY2 <- as.numeric(df$ALCDAY2)

df$ALCTX <- as.numeric(df$ALCTX)
df$ALCTX1 <- as.numeric(df$ALCTX1)
df$ALCTX2 <- as.numeric(df$ALCTX2)

#binge alcohol on a typical day
#binge baseline
df$binge <- ifelse(df$ALCDAY==0, 0, ifelse(df$ALCTX<4, 0, ifelse(df$ALCTX>3, 1, NA)))
#binge FU1 
df$binge1 <- ifelse(df$ALCDAY1==0, 0, ifelse(df$ALCTX1<4, 0, ifelse(df$ALCTX1>3, 1, NA)))
#binge FU2
df$binge2 <- ifelse(df$ALCDAY2==0, 0, ifelse(df$ALCTX2<4, 0, ifelse(df$ALCTX2>3, 1, NA)))

#any stimulant injection
#any stimulant injection baseline
df$ANYSTIM <- ifelse(df$CRKINJ=="Yes" | df$CCINJ=="Yes" | df$MTINJ=="Yes" | df$STINJ=="Yes", 1, ifelse(df$CRKINJ=="No" & df$CCINJ=="No" & df$MTINJ=="No" & df$STINJ=="No", 0, NA))
#any stimulant injection FU1
df$ANYSTIM1 <- ifelse(df$CRKINJ1=="Yes" | df$CCINJ1=="Yes" | df$MTINJ1=="Yes" | df$STINJ1=="Yes", 1, ifelse(df$CRKINJ1=="No" & df$CCINJ1=="No" & df$MTINJ1=="No" & df$STINJ1=="No", 0, NA))
#any stimulant injection FU2
df$ANYSTIM2 <- ifelse(df$CRKINJ2=="Yes" | df$CCINJ2=="Yes" | df$MTINJ2=="Yes" | df$STINJ2=="Yes", 1, ifelse(df$CRKINJ2=="No" & df$CCINJ2=="No" & df$MTINJ2=="No" & df$STINJ2=="No", 0, NA))

#any opioid injection
#any opioid injection baseline
df$ANYOPIATE <- ifelse(df$HRINJ=="Yes" | df$OPINJ=="Yes", 1, ifelse(df$HRINJ=="No" & df$OPINJ=="No", 0, NA))
#any opioid injection FU1
df$ANYOPIATE1 <- ifelse(df$HRINJ1=="Yes" | df$OPINJ1=="Yes", 1, ifelse(df$HRINJ1=="No" & df$OPINJ1=="No", 0, NA))
#any opioid injection FU2
df$ANYOPIATE2 <- ifelse(df$HRINJ2=="Yes" | df$OPINJ2=="Yes", 1, ifelse(df$HRINJ2=="No" & df$OPINJ2=="No", 0, NA))

#clean up data types
df$MOSHOME <- as.numeric(df$MOSHOME)
df$MOSHOME1 <- as.numeric(df$MOSHOME1)
df$MOSHOME[is.na(df$MOSHOME)] <- 0
df$MOSHOME1[is.na(df$MOSHOME1)] <- 0
df$AGE <- as.numeric(df$AGE)
df$Rshare1 <- factor(df$Rshare1)

#create key variables not asked at baseline
df$ARREST <- rep(NA)
df$POLICE <- rep(NA)
df$JAIL <- rep(NA)

#select variables
dfs <- df %>%
  dplyr::select("SUBJECT", "FU1", "FU2", "GENDER", "AGE", "RACELG", "HOMELESS", "HOMELESS1", "HOMELESS2", "MOSHOME", "MOSHOME1", "MOSHOM2", "RECSHR", "RECSHR1", "RECSHR2", "PUBINJ", "PUBINJ1", "PUBINJ2", "IJWOTH", "IJWOTH1", "IJWOTH2", "POLICE", "POLICE1", "POLICE2", "ARREST", "ARREST1", "ARREST2", "JAIL", "JAIL1", "JAIL2", "Rshare", "Rshare1", "Rshare2", "binge", "binge1", "binge2", "ANYSTIM", "ANYSTIM1", "ANYSTIM2", "ANYOPIATE", "ANYOPIATE1", "ANYOPIATE2")

#look at missingness
missing <- data.frame(md.pattern(dfs))

#remove subjects with NA for exposure or outcome 
dfs <- subset(dfs, SUBJECT!=4394) 
dfs <- subset(dfs, SUBJECT!=4457) 
dfs <- subset(dfs, SUBJECT!=5055)
dfs <- subset(dfs, SUBJECT!=5267)
dfs <- subset(dfs, SUBJECT!=5276)
dfs <- subset(dfs, SUBJECT!=5277)

# #figure out any additional cases that will be dropped from glms below
# dfsglm <- dfs %>%
#   dplyr::select("SUBJECT", "GENDER", "AGE", "HOMELESS", "MOSHOME", "PUBINJ", "IJWOTH","RECSHR", "binge", "ANYSTIM", "ANYOPIATE")
# dfsglm$SUBJECT[which(! complete.cases(dfsglm))]

#impute missing covariates
impute <- c("SUBJECT", "GENDER", "AGE", "IJWOTH", "IJWOTH1", "IJWOTH2", "POLICE1", "POLICE2", "ARREST1", "ARREST2", "JAIL1", "JAIL2", "binge", "ANYSTIM", "ANYOPIATE", "binge1", "ANYSTIM1", "ANYOPIATE1", "binge2", "ANYSTIM2", "ANYOPIATE2")
keeps <- c("GENDER", "AGE", "IJWOTH", "IJWOTH1", "IJWOTH2", "POLICE1", "POLICE2", "ARREST1", "ARREST2", "JAIL1", "JAIL2", "binge", "ANYSTIM", "ANYOPIATE", "binge1", "ANYSTIM1", "ANYOPIATE1", "binge2", "ANYSTIM2", "ANYOPIATE2")
imputation <- mice(dfs[, (names(dfs) %in% impute)], m=5, maxit=5, printFlag=TRUE, seed = 242)
dfs1 <- complete(imputation, 1)
dfs1 <- merge(dfs1, dfs[, !(names(dfs) %in% keeps)], by = "SUBJECT")
dfs2 <- complete(imputation, 2)
dfs2 <- merge(dfs2, dfs[, !(names(dfs) %in% keeps)], by = "SUBJECT")
dfs3 <- complete(imputation, 3)
dfs3 <- merge(dfs3, dfs[, !(names(dfs) %in% keeps)], by = "SUBJECT")
dfs4 <- complete(imputation, 4)
dfs4 <- merge(dfs4, dfs[, !(names(dfs) %in% keeps)], by = "SUBJECT")
dfs5 <- complete(imputation, 5)
dfs5 <- merge(dfs5, dfs[, !(names(dfs) %in% keeps)], by = "SUBJECT")

#reweight sample to address LTFU
I_ABC <- dfs$FU1 == "Yes" & dfs$FU2 == 1
gFU1a <- glm(FU1 ~ RECSHR + PUBINJ + HOMELESS + JAIL + IJWOTH + GENDER + AGE + ANYSTIM, family = "binomial", data = dfs1, na.action = na.omit)
gFU1b <- glm(FU1 ~ RECSHR + PUBINJ + HOMELESS + JAIL + IJWOTH + GENDER + AGE + ANYSTIM, family = "binomial", data = dfs2, na.action = na.omit)
gFU1c <- glm(FU1 ~ RECSHR + PUBINJ + HOMELESS + JAIL + IJWOTH + GENDER + AGE + ANYSTIM, family = "binomial", data = dfs3, na.action = na.omit)
gFU1d <- glm(FU1 ~ RECSHR + PUBINJ + HOMELESS + JAIL + IJWOTH + GENDER + AGE + ANYSTIM, family = "binomial", data = dfs4, na.action = na.omit)
gFU1e <- glm(FU1 ~ RECSHR + PUBINJ + HOMELESS + JAIL + IJWOTH + GENDER + AGE + ANYSTIM, family = "binomial", data = dfs5, na.action = na.omit)
pFU1a <- predict(gFU1a, type = "response")
pFU1b <- predict(gFU1b, type = "response")
pFU1c <- predict(gFU1c, type = "response")
pFU1d <- predict(gFU1d, type = "response")
pFU1e <- predict(gFU1e, type = "response")
impFU1 <-data.frame(pFU1a, pFU1b, pFU1c, pFU1d, pFU1e)
dfs$pFU1 <- rowMeans(impFU1)
gFU2a <- glm(FU2 ~ FU1 + RECSHR + PUBINJ + HOMELESS + JAIL + IJWOTH + GENDER + AGE + ANYSTIM, family = "binomial", data = dfs1, na.action = na.omit) 
gFU2b <- glm(FU2 ~ FU1 + RECSHR + PUBINJ + HOMELESS + JAIL + IJWOTH + GENDER + AGE + ANYSTIM, family = "binomial", data = dfs2, na.action = na.omit) 
gFU2c <- glm(FU2 ~ FU1 + RECSHR + PUBINJ + HOMELESS + JAIL + IJWOTH + GENDER + AGE + ANYSTIM, family = "binomial", data = dfs3, na.action = na.omit) 
gFU2d <- glm(FU2 ~ FU1 + RECSHR + PUBINJ + HOMELESS + JAIL + IJWOTH + GENDER + AGE + ANYSTIM, family = "binomial", data = dfs4, na.action = na.omit) 
gFU2e <- glm(FU2 ~ FU1 + RECSHR + PUBINJ + HOMELESS + JAIL + IJWOTH + GENDER + AGE + ANYSTIM, family = "binomial", data = dfs5, na.action = na.omit) 
pFU2a <- predict(gFU2a, type = "response")
pFU2b <- predict(gFU2b, type = "response")
pFU2c <- predict(gFU2c, type = "response")
pFU2d <- predict(gFU2d, type = "response")
pFU2e <- predict(gFU2e, type = "response")
impFU2 <-data.frame(pFU2a, pFU2b, pFU2c, pFU2d, pFU2e)
dfs$pFU2 <- rowMeans(impFU2)
dfs$w <- I_ABC/(dfs$pFU1 * dfs$pFU2)
rm(gFU1a, gFU1b, gFU1c, gFU1d, gFU1e, gFU2a, gFU2b, gFU2c, gFU2d, gFU2e, pFU1a, pFU1b, pFU1c, pFU1d, pFU1e, pFU2a, pFU2b, pFU2c, pFU2d, pFU2e, impFU1, impFU2)

#select people with no LTFU (complete case)
#dfc <- subset(df, FU2==1 & FU1=="Yes")

#make dataset long format
dfslong <- reshape(dfs, idvar = "SUBJECT", varying = list(c("HOMELESS", "HOMELESS1", "HOMELESS2"), c("MOSHOME", "MOSHOME1", "MOSHOM2"), c("RECSHR", "RECSHR1", "RECSHR2"), c("PUBINJ", "PUBINJ1", "PUBINJ2"), c("IJWOTH", "IJWOTH1", "IJWOTH2"), c("POLICE", "POLICE1", "POLICE2"), c("ARREST", "ARREST1", "ARREST2"), c("JAIL", "JAIL1", "JAIL2"), c("binge", "binge1", "binge2"), c("ANYSTIM", "ANYSTIM1", "ANYSTIM2"), c("ANYOPIATE", "ANYOPIATE1", "ANYOPIATE2")), timevar = "VISIT", v.names = c("HOMELESS", "MOSHOME", "TIMESHARE", "PUBINJ", "IJWOTH", "POLICE", "ARREST", "JAIL", "binge", "ANYSTIM", "ANYOPIATE"), ids = "SUBJECT", times = c("baseline", "FU1", "FU2"), direction = "long")

#update variable types
dfslong$TIMESHARE <- as.numeric(dfslong$TIMESHARE)
dfslong$POLICE <- as.factor(dfslong$POLICE)
dfslong$ARREST <- as.factor(dfslong$ARREST)
dfslong$JAIL <- as.factor(dfslong$JAIL)
dfslong$VISIT <- as.factor(dfslong$VISIT)
dfslong$MOSHOME <- as.numeric(dfslong$MOSHOME)

dfslong$PUBINJord <- as.numeric(ifelse(dfslong$PUBINJ=="Never (0% of the time)", 0, ifelse(dfslong$PUBINJ=="Occasionally (less than 25% of the time)", 1, ifelse(dfslong$PUBINJ=="Sometimes (25% to 74% of the time)", 2, ifelse(dfslong$PUBINJ=="Usually (75% to 99% of the time)", 3, ifelse(dfslong$PUBINJ=="Always (100% of the time)", 4 ,NA))))))

dfslong$PUBINJ_3cat <- as.factor(ifelse(dfslong$PUBINJ=="Never (0% of the time)", 0, ifelse(dfslong$PUBINJ=="Occasionally (less than 25% of the time)" | dfslong$PUBINJ=="Sometimes (25% to 74% of the time)", 1, ifelse(dfslong$PUBINJ=="Usually (75% to 99% of the time)" | dfslong$PUBINJ=="Always (100% of the time)", 2, NA))))

dfslong$IJWOTHord <- as.numeric(ifelse(dfslong$IJWOTH=="Never (0% of the time)", 0, ifelse(dfslong$IJWOTH=="Occasionally (less than 25% of the time)", 1, ifelse(dfslong$IJWOTH=="Sometimes (25% to 74% of the time)", 2, ifelse(dfslong$IJWOTH=="Usually (75% to 99% of the time)", 3, ifelse(dfslong$IJWOTH=="Always (100% of the time)", 4, NA))))))

dfslong$YRSHOME <- dfslong$MOSHOME/12
```

Analysis with no weights:

```{r analysis no weights, include=TRUE, cache=TRUE}
######################################################################
########NOTE THAT RIGHT NOW WE ARE NOT REWEIGHTING THE SAMPLE#########
######################################################################

#gee model
library(gee)
modelgee <- gee(TIMESHARE ~ PUBINJord*YRSHOME + GENDER + AGE + ANYSTIM + ANYOPIATE + binge, SUBJECT, data = dfslong, family = poisson, corstr = "exchangeable", na.action = na.omit)
summary(modelgee)

#mixed effects models

#poisson
modelpoisson <- glmer(TIMESHARE ~ PUBINJord*YRSHOME + GENDER + AGE + ANYSTIM + ANYOPIATE + binge + (1|SUBJECT), family = "poisson", data = dfslong, na.action = na.omit)
summary(modelpoisson)
exp(summary(modelpoisson)$coefficients)

#negative binomial
modelnb <- glmer.nb(TIMESHARE ~ PUBINJord*YRSHOME + GENDER + AGE + ANYSTIM + ANYOPIATE + binge + (1|SUBJECT), data = dfslong, na.action = na.omit)
summary(modelnb)
exp(summary(modelnb)$coefficients)

#using confint.merMod from lme4 to get 95% CI for public injecting. I think we want method="profile" instead of method="Wald" but I couldn't get it to work.
est <- confint(modelnb, "PUBINJord", level=0.95, method="Wald")
exp(est)
```

Compare poisson and negative binomial models. I think it appears NB is better.
```{r}
lrtest(modelpoisson, modelnb)
AIC(modelpoisson, modelnb)
```


Playing around with public injecting as categorical instead of ordinal.
```{r}
#gee
modelgee_categorical <- gee(TIMESHARE ~ PUBINJ_3cat*YRSHOME + GENDER + AGE + ANYSTIM + ANYOPIATE + binge, SUBJECT, data = dfslong, family = poisson, corstr = "exchangeable", na.action = na.omit)
summary(modelgee_categorical)

#poisson
modelpoisson_categorical <- glmer(TIMESHARE ~ PUBINJ_3cat*YRSHOME + GENDER + AGE + ANYSTIM + ANYOPIATE + binge + (1|SUBJECT), family = "poisson", data = dfslong, na.action = na.omit)
summary(modelpoisson_categorical)
exp(summary(modelpoisson_categorical)$coefficients)

#negative binomial
modelnb_categorical <- glmer.nb(TIMESHARE ~ PUBINJ_3cat*YRSHOME + GENDER + AGE + ANYSTIM + ANYOPIATE + binge + (1|SUBJECT), data = dfslong, na.action = na.omit)
summary(modelnb_categorical)
exp(summary(modelnb_categorical)$coefficients)

#using confint.merMod from lme4 to get 95% CI for public injecting. I think we want method="profile" instead of method="Wald" but I couldn't get it to work.
est_categorical <- confint(modelnb_categorical, c("PUBINJ_3cat1", "PUBINJ_3cat2"), level=0.95, method="Wald")
exp(est_categorical)
```

